File: ../TSP_assignment_task_benchmark_data/a280.tsp
NNH : 3406.29
NNH + 2-opt : 2768.37
NNH + Node Shift : 3101.55
NNH + Node Swap : 2937.93
Random Insertion : 3040.39
Random Insertion + 2-opt : 2887.79
Random Insertion + Node Shift : 2873.55
Random Insertion + Node Swap : 2977.95
Greedy approach : 5095.26
Greedy approach + 2-opt : 3065.73
Greedy approach + Node Shift : 3337
Greedy approach + Node Swap : 3986.38
