File: ../TSP_assignment_task_benchmark_data/berlin52.tsp
NNH : 22262.9
NNH + 2-opt : 8302.1
NNH + Node Shift : 8183.43
NNH + Node Swap : 10513.4
Random Insertion : 8102.06
Random Insertion + 2-opt : 7986.42
Random Insertion + Node Shift : 7979.52
Random Insertion + Node Swap : 7993.5
Greedy approach : 28059.9
Greedy approach + 2-opt : 8106.15
Greedy approach + Node Shift : 8704.45
Greedy approach + Node Swap : 13017.5
