File: ../TSP_assignment_task_benchmark_data/bier127.tsp
NNH : 418626
NNH + 2-opt : 129874
NNH + Node Shift : 142984
NNH + Node Swap : 184420
Random Insertion : 136964
Random Insertion + 2-opt : 141894
Random Insertion + Node Shift : 141710
Random Insertion + Node Swap : inf
Greedy approach : 577255
Greedy approach + 2-opt : 128583
Greedy approach + Node Shift : 139926
Greedy approach + Node Swap : 197521
