File: ../TSP_assignment_task_benchmark_data/ch130.tsp
NNH : 48404
NNH + 2-opt : 6719.41
NNH + Node Shift : 7951.82
NNH + Node Swap : 12784.6
Random Insertion : 6873.28
Random Insertion + 2-opt : 6535.56
Random Insertion + Node Shift : 6522.44
Random Insertion + Node Swap : 6546.51
Greedy approach : 46273.5
Greedy approach + 2-opt : 6656.93
Greedy approach + Node Shift : 7930.98
Greedy approach + Node Swap : 12061.3
