File: ../TSP_assignment_task_benchmark_data/ch150.tsp
NNH : 52833.5
NNH + 2-opt : 7373.75
NNH + Node Shift : 8126.11
NNH + Node Swap : 12419.7
Random Insertion : 7162.71
Random Insertion + 2-opt : 7085.14
Random Insertion + Node Shift : 7019.47
Random Insertion + Node Swap : 7116.82
Greedy approach : 51018
Greedy approach + 2-opt : 7348.36
Greedy approach + Node Shift : 8697.85
Greedy approach + Node Swap : 12305.3
