File: ../TSP_assignment_task_benchmark_data/eil101.tsp
NNH : 2105.11
NNH + 2-opt : 743.274
NNH + Node Shift : 781.182
NNH + Node Swap : 975.086
Random Insertion : 712.206
Random Insertion + 2-opt : 689.484
Random Insertion + Node Shift : 690.512
Random Insertion + Node Swap : 699.889
Greedy approach : 2827.75
Greedy approach + 2-opt : 727.867
Greedy approach + Node Shift : 739.588
Greedy approach + Node Swap : 906.132
