File: ../TSP_assignment_task_benchmark_data/eil51.tsp
NNH : 1406.5
NNH + 2-opt : 463.339
NNH + Node Shift : 494.457
NNH + Node Swap : 635.913
Random Insertion : 469.891
Random Insertion + 2-opt : 471.666
Random Insertion + Node Shift : 449.598
Random Insertion + Node Swap : 471.666
Greedy approach : 1731.18
Greedy approach + 2-opt : 476.972
Greedy approach + Node Shift : 494.068
Greedy approach + Node Swap : 576.914
