File: ../TSP_assignment_task_benchmark_data/eil76.tsp
NNH : 2035.67
NNH + 2-opt : 608.422
NNH + Node Shift : 615.164
NNH + Node Swap : 772.846
Random Insertion : 610.501
Random Insertion + 2-opt : 604.4
Random Insertion + Node Shift : 592.58
Random Insertion + Node Swap : 607.272
Greedy approach : 2404.87
Greedy approach + 2-opt : 607.657
Greedy approach + Node Shift : 653.567
Greedy approach + Node Swap : 777.494
