File: ../TSP_assignment_task_benchmark_data/kroA100.tsp
NNH : 194153
NNH + 2-opt : 24098
NNH + Node Shift : 26532.7
NNH + Node Swap : 55011.8
Random Insertion : 22906.7
Random Insertion + 2-opt : 22181.2
Random Insertion + Node Shift : 21567
Random Insertion + Node Swap : 22243.8
Greedy approach : 157139
Greedy approach + 2-opt : 25371
Greedy approach + Node Shift : 29829.3
Greedy approach + Node Swap : 54893.3
