File: ../TSP_assignment_task_benchmark_data/kroB100.tsp
NNH : 157587
NNH + 2-opt : 24014.4
NNH + Node Shift : 27895.6
NNH + Node Swap : 40108.8
Random Insertion : 25922.7
Random Insertion + 2-opt : 23513.7
Random Insertion + Node Shift : 23255.7
Random Insertion + Node Swap : 23713.3
Greedy approach : 183332
Greedy approach + 2-opt : 26933.7
Greedy approach + Node Shift : 31652.5
Greedy approach + Node Swap : 44881
