File: ../TSP_assignment_task_benchmark_data/kroC100.tsp
NNH : 183891
NNH + 2-opt : 22679.7
NNH + Node Shift : 26132.5
NNH + Node Swap : 45732.2
Random Insertion : 22053.1
Random Insertion + 2-opt : 21375.1
Random Insertion + Node Shift : 21714.8
Random Insertion + Node Swap : 21375.1
Greedy approach : 159563
Greedy approach + 2-opt : 22159.2
Greedy approach + Node Shift : 26570.2
Greedy approach + Node Swap : 44965
