File: ../TSP_assignment_task_benchmark_data/kroD100.tsp
NNH : 166110
NNH + 2-opt : 23557.9
NNH + Node Shift : 24564.2
NNH + Node Swap : 46699.2
Random Insertion : 25741.7
Random Insertion + 2-opt : 23506.4
Random Insertion + Node Shift : 22521.7
Random Insertion + Node Swap : 23746.1
Greedy approach : 164029
Greedy approach + 2-opt : 25372.5
Greedy approach + Node Shift : 29061.7
Greedy approach + Node Swap : 38316.4
