File: ../TSP_assignment_task_benchmark_data/kroE100.tsp
NNH : 183384
NNH + 2-opt : 23692.6
NNH + Node Shift : 25092.3
NNH + Node Swap : 43599.1
Random Insertion : 27766.2
Random Insertion + 2-opt : 23461.5
Random Insertion + Node Shift : 24649.1
Random Insertion + Node Swap : 24764.5
Greedy approach : 174304
Greedy approach + 2-opt : 25998.7
Greedy approach + Node Shift : 30243.4
Greedy approach + Node Swap : 43363.8
