File: ../TSP_assignment_task_benchmark_data/lin105.tsp
NNH : 36640.2
NNH + 2-opt : 16325.4
NNH + Node Shift : 16756.6
NNH + Node Swap : 24584.1
Random Insertion : 16422
Random Insertion + 2-opt : 16092.2
Random Insertion + Node Shift : 15979.6
Random Insertion + Node Swap : 16244.2
Greedy approach : 57979.7
Greedy approach + 2-opt : 15090.1
Greedy approach + Node Shift : 17414.6
Greedy approach + Node Swap : 21793.6
