File: ../TSP_assignment_task_benchmark_data/lin318.tsp
NNH : 120043
NNH + 2-opt : 47094.9
NNH + Node Shift : 60813
NNH + Node Swap : 80086.8
Random Insertion : 46186.6
Random Insertion + 2-opt : 45957.8
Random Insertion + Node Shift : 45484.9
Random Insertion + Node Swap : 45972.4
Greedy approach : 193384
Greedy approach + 2-opt : 46434.2
Greedy approach + Node Shift : 60690.7
Greedy approach + Node Swap : 74301.4
