File: ../TSP_assignment_task_benchmark_data/pr124.tsp
NNH : 116736
NNH + 2-opt : 73328.2
NNH + Node Shift : 98206.6
NNH + Node Swap : 107148
Random Insertion : 73505.3
Random Insertion + 2-opt : 73288.7
Random Insertion + Node Shift : 73208
Random Insertion + Node Swap : 73288.7
Greedy approach : 194076
Greedy approach + 2-opt : 74506.3
Greedy approach + Node Shift : 76208.3
Greedy approach + Node Swap : 80710
