File: ../TSP_assignment_task_benchmark_data/pr144.tsp
NNH : 104283
NNH + 2-opt : 71520.6
NNH + Node Shift : 91067.3
NNH + Node Swap : 103078
Random Insertion : 72008.4
Random Insertion + 2-opt : 70891.4
Random Insertion + Node Shift : 71216.1
Random Insertion + Node Swap : 72008.4
Greedy approach : 187265
Greedy approach + 2-opt : 72274.2
Greedy approach + Node Shift : 83579.5
Greedy approach + Node Swap : 102149
