File: ../TSP_assignment_task_benchmark_data/pr76.tsp
NNH : 151298
NNH + 2-opt : 112677
NNH + Node Shift : 139350
NNH + Node Swap : 151298
Random Insertion : 120457
Random Insertion + 2-opt : 115733
Random Insertion + Node Shift : 119973
Random Insertion + Node Swap : 120053
Greedy approach : 231769
Greedy approach + 2-opt : 116613
Greedy approach + Node Shift : inf
Greedy approach + Node Swap : 154485
