File: ../TSP_assignment_task_benchmark_data/rat195.tsp
NNH : 4056.53
NNH + 2-opt : 2491.03
NNH + Node Shift : 2654.67
NNH + Node Swap : 3620.99
Random Insertion : 2588.83
Random Insertion + 2-opt : 2574.06
Random Insertion + Node Shift : 2488.01
Random Insertion + Node Swap : 2581.93
Greedy approach : 5289.63
Greedy approach + 2-opt : 2598.45
Greedy approach + Node Shift : 2667.56
Greedy approach + Node Swap : 3303.65
