File: ../TSP_assignment_task_benchmark_data/rat99.tsp
NNH : 2143.02
NNH + 2-opt : 1350.88
NNH + Node Shift : 1382.34
NNH + Node Swap : 1999.74
Random Insertion : 1414.51
Random Insertion + 2-opt : 1326.6
Random Insertion + Node Shift : 1314.34
Random Insertion + Node Swap : 1378.23
Greedy approach : 2773.02
Greedy approach + 2-opt : 1324.71
Greedy approach + Node Shift : 1424.89
Greedy approach + Node Swap : 1605.91
