File: ../TSP_assignment_task_benchmark_data/st70.tsp
NNH : 3546.32
NNH + 2-opt : 738.322
NNH + Node Shift : 932.69
NNH + Node Swap : 1297.51
Random Insertion : 881.645
Random Insertion + 2-opt : 709.859
Random Insertion + Node Shift : 788.824
Random Insertion + Node Swap : 802.35
Greedy approach : 3538.01
Greedy approach + 2-opt : 768.823
Greedy approach + Node Shift : 821.38
Greedy approach + Node Swap : 1178.68
